name: "🚒 Abertura de Issues para os ambientes de Dev e Homol"
description: Aqui você irá abrir uma issue para o time de SRE.
title: "🚒 [Issue] - <Título da issue>"
labels: [
  "Issue"
]
assignees:
  - ${{github.author}}
body:
  - type: dropdown
    id: ambiente
    attributes:
      label: "Ambiente"
      description: Qual ambiente impactado ?
      multiple: true
      options:
        - Dev
        - Homol
    validations:
      required: true
  - type: dropdown
    id: sigla
    attributes:
      label: "Sigla"
      description: Em qual sigla é o impacto ?
      multiple: true
      options:
        - EJ9
        - EV8
        - PW2
        - IM2
        - ES2
        - OU3
        - DY5
        - EM8
        - EQ3
        - HW(BUREAU)
        - EK4(CARTÕES)
        - AQ5(SIMILTY)
        - AQ4
        - DY9
        - EK7
        - HOME
        - PISMO
        - AUTH-PARTNER
        - CARONTE
        - CONSUL
        - GIT
        - JENKINS-PIPELINE
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "flow"
      description: Forneça um Trace-ID, Flow-ID ou Session-ID.
      placeholder: Por favor, forneça um Trace-ID, Flow-ID ou Session-ID.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Descrição"
      description: Descreva o que ocorre na sua experiência.
      placeholder: Por favor, forneça uma descrição clara e concisa do problema. Inclua todos os contextos e exemplos relevantes.
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Passos para reproduzir"
      description: Descreva como você gostaria que o sistema se comportasse.
      value: |
          1. Passo 1
          2. Passo 2
          3. Passo 3
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: Se aplicável, inclua screenshots para ajudar a explicar o problema.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Forneça os logs do seu erro.
      render: bash
    validations:
      required: false
